{% set version = '0.4-13' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-quantmod
  version: {{ version|replace("-", "_") }}

source:
  fn: quantmod_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/quantmod_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/quantmod/quantmod_{{ version }}.tar.gz
  sha256: 60fb13821c9d8d5bea34223b18757f04787f4440cb82946bb9559d6fd26b5499

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ttr >=0.2
    - r-curl
    - r-xts >=0.9_0
    - r-zoo
  run:
    - r-base
    - r-ttr >=0.2
    - r-curl
    - r-xts >=0.9_0
    - r-zoo

test:
  commands:
    - $R -e "library('quantmod')"           # [not win]
    - "\"%R%\" -e \"library('quantmod')\""  # [win]

about:
  home: http://www.quantmod.com https://github.com/joshuaulrich/quantmod
  license: GPL-3
  summary: Specify, build, trade, and analyse quantitative financial trading strategies.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
