{% set version = "0.4-16" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-quantmod
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/quantmod_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/quantmod/quantmod_{{ version }}.tar.gz
  sha256: 826de2c821799cf9ced09d99d277d91aeb74eec75b5a89fb533ee4a5505e858a

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ttr >=0.2
    - r-curl
    - r-xts >=0.9_0
    - r-zoo
  run:
    - r-base
    - r-ttr >=0.2
    - r-curl
    - r-xts >=0.9_0
    - r-zoo

test:
  commands:
    - $R -e "library('quantmod')"           # [not win]
    - "\"%R%\" -e \"library('quantmod')\""  # [win]

about:
  home: http://www.quantmod.com https://github.com/joshuaulrich/quantmod
  license: GPL-3
  summary: Specify, build, trade, and analyse quantitative financial trading strategies.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: quantmod
# Type: Package
# Title: Quantitative Financial Modelling Framework
# Version: 0.4-15
# Authors@R: c( person(given=c("Jeffrey","A."), family="Ryan", role=c("aut","cph")), person(given=c("Joshua","M."), family="Ulrich", role=c("cre","aut"), email="josh.m.ulrich@gmail.com"), person(given="Wouter", family="Thielen", role="ctb"), person(given="Paul", family="Teetor", role="ctb"), person(given="Steve", family="Bronder", role="ctb") )
# Depends: R (>= 3.2.0), xts(>= 0.9-0), zoo, TTR(>= 0.2), methods
# Imports: curl
# Suggests: DBI,RMySQL,RSQLite,timeSeries,XML,downloader,jsonlite(>= 1.1)
# Description: Specify, build, trade, and analyse quantitative financial trading strategies.
# LazyLoad: yes
# License: GPL-3
# URL: http://www.quantmod.com https://github.com/joshuaulrich/quantmod
# BugReports: https://github.com/joshuaulrich/quantmod/issues
# NeedsCompilation: no
# Packaged: 2019-06-17 10:38:37 UTC; josh
# Author: Jeffrey A. Ryan [aut, cph], Joshua M. Ulrich [cre, aut], Wouter Thielen [ctb], Paul Teetor [ctb], Steve Bronder [ctb]
# Maintainer: Joshua M. Ulrich <josh.m.ulrich@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-06-17 13:20:04 UTC
