{% set version = "0.4.26" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-quantmod
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/quantmod_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/quantmod/quantmod_{{ version }}.tar.gz
  sha256: 396c5d3241f77911d9f7738a60a9d728ed25b3dbce2fd92f5b11f9fcbcb8bb98

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip      # [win]
  host:
    - r-base
    - r-curl
    - r-jsonlite >=1.1
    - r-ttr >=0.2
    - r-xts >=0.9_0
    - r-zoo
  run:
    - r-base
    - r-curl
    - r-jsonlite >=1.1
    - r-ttr >=0.2
    - r-xts >=0.9_0
    - r-zoo

test:
  commands:
    - $R -e "library('quantmod')"           # [not win]
    - "\"%R%\" -e \"library('quantmod')\""  # [win]

about:
  home: http://www.quantmod.com
  dev_url: https://github.com/joshuaulrich/quantmod
  license: GPL-3.0-only
  summary: Specify, build, trade, and analyse quantitative financial trading strategies.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
